server.port=${APP_PORT}

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.open-in-view=false

calculator.url=${CALCULATOR_URL}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic.finish-registration=${KAFKA_TOPIC_FINISH_REGISTRATION}
kafka.topic.create-documents=${KAFKA_TOPIC_CREATE_DOCUMENTS}
kafka.topic.send-documents=${KAFKA_TOPIC_SEND_DOCUMENTS}
kafka.topic.send-ses=${KAFKA_TOPIC_SEND_SES}
kafka.topic.credit-issued=${KAFKA_TOPIC_CREDIT_ISSUED}
kafka.topic.statement-denied=${KAFKA_TOPIC_STATEMENT_DENIED}

error.business-code=${ERROR_BUSINESS_CODE}
error.validation-code=${ERROR_VALIDATION_CODE}
error.server-code=${ERROR_SERVER_CODE}
