spring.application.name=deal

spring.messages.encoding=UTF-8
spring.profiles.active=dev
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
error.business-code=${ERROR_BUSINESS_CODE:422}
error.validation-code=${ERROR_VALIDATION_CODE:400}
error.server-code=${ERROR_SERVER_CODE:500}


