server.port=8082
logging.level.root.com.credithandler = debug

spring.datasource.url=jdbc:postgresql://localhost:5432/credit_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

calculator.url=http://localhost:8081

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

kafka.topic.finish-registration=${KAFKA_TOPIC_FINISH_REGISTRATION:finish-registration}

error.business-code=422
error.validation-code=400
error.server-code=500
