spring.application.name=statement
spring.messages.encoding=UTF-8

server.port=${APP_PORT}

deal.url=${DEAL_URL}

error.business-code=${ERROR_BUSINESS_CODE}
error.validation-code=${ERROR_VALIDATION_CODE}
error.server-code=${ERROR_SERVER_CODE}
