
error.response-timestamp=${ERROR_RESPONSE_TIMESTAMP}
error.response-status=${ERROR_RESPONSE_STATUS}
error.response-error=${ERROR_RESPONSE_ERROR}
error.response-message=${ERROR_RESPONSE_MESSAGE}
error.response-field=${ERROR_RESPONSE_FIELD}
error.response-errors=${ERROR_RESPONSE_ERRORS}

error.business-error-title=${ERROR_BUSINESS_TITLE}
error.validation-error-title=${ERROR_VALIDATION_TITLE}
error.server-error-title=${ERROR_SERVER_TITLE}
error.server-error-message=${ERROR_SERVER_MESSAGE}