spring.application.name=calculator
server.port=${APP_PORT}

loan.base-interest=${BASE_INTEREST}
loan.salary-decrease=${IF_SALARY_DECREASE}
loan.insurance-decrease=${IF_INSURANCE_DECREASE}

scoring.min-age=${CLIENT_MIN_AGE}
scoring.max-age=${CLIENT_MAX_AGE}

scoring.self-employed-increase=${SELF_EMPLOYED_RATE_INCREASE}
scoring.company-owner-increase=${COMPANY_OWNER_RATE_INCREASE}

scoring.middle-manager-decrease=${MIDDLE_MANAGER_RATE_DECREASE}
scoring.top-manager-decrease=${TOP_MANAGER_RATE_DECREASE}

scoring.married-decrease=${MARRIED_RATE_DECREASE}
scoring.divorced-increase=${DIVORCED_RATE_INCREASE}

scoring.max-salary-multiple=${MAX_MULTIPLE_OF_SALARY}

scoring.female-age-min=${GENDER_FEMALE_AGE_MIN}
scoring.female-age-max=${GENDER_FEMALE_AGE_MAX}
scoring.male-age-min=${GENDER_MALE_AGE_MIN}
scoring.male-age-max=${GENDER_MALE_AGE_MAX}

scoring.female-decrease=${GENDER_FEMALE_RATE_DECREASE}
scoring.male-decrease=${GENDER_MALE_RATE_DECREASE}
scoring.non-binary-increase=${GENDER_NON_BINARY_RATE_INCREASE}

scoring.min-total-work-experience=${WORK_EXPERIENCE_TOTAL_MIN_MONTHS}
scoring.min-current-work-experience=${WORK_EXPERIENCE_CURRENT_MIN_MONTHS}

# Error
error.business-code=${ERROR_BUSINESS_CODE}
error.validation-code=${ERROR_VALIDATION_CODE}
error.server-code=${ERROR_SERVER_CODE}

error.response-timestamp=${ERROR_RESPONSE_TIMESTAMP}
error.response-status=${ERROR_RESPONSE_STATUS}
error.response-error=${ERROR_RESPONSE_ERROR}
error.response-message=${ERROR_RESPONSE_MESSAGE}
error.response-field=${ERROR_RESPONSE_FIELD}
error.response-errors=${ERROR_RESPONSE_ERRORS}

error.business-error-title=${ERROR_BUSINESS_TITLE}
error.validation-error-title=${ERROR_VALIDATION_TITLE}
error.server-error-title=${ERROR_SERVER_TITLE}
error.server-error-message=${ERROR_SERVER_MESSAGE}

error.unemployed-message=${ERROR_UNEMPLOYED_MESSAGE}
error.loan-amount-message=${ERROR_LOAN_AMOUNT_MESSAGE}
error.age-message=${ERROR_AGE_MESSAGE}
error.total-experience-message=${ERROR_TOTAL_EXPERIENCE_MESSAGE}
error.current-experience-message=${ERROR_CURRENT_EXPERIENCE_MESSAGE}
error.employment-status-null-message=${ERROR_EMPLOYMENT_STATUS_NULL_MESSAGE}
error.position-null-message=${ERROR_POSITION_NULL_MESSAGE}
error.marital-status-null-message=${ERROR_MARITAL_STATUS_NULL_MESSAGE}
error.birthdate-null-message=${ERROR_BIRTHDATE_NULL_MESSAGE}
error.zero-rate-message=${ERROR_ZERO_RATE_MESSAGE}
error.negative-rate-message=${ERROR_NEGATIVE_RATE_MESSAGE}
error.invalid-term-message=${ERROR_INVALID_TERM_MESSAGE}
error.invalid-amount-message=${ERROR_INVALID_AMOUNT_MESSAGE}

# Log ERROR
error.log-employment-status=${ERROR_LOG_EMPLOYMENT_STATUS}
error.log-loan-amount=${ERROR_LOG_LOAN_AMOUNT}
error.log-age=${ERROR_LOG_AGE}
error.log-total-experience=${ERROR_LOG_TOTAL_EXPERIENCE}
error.log-current-experience=${ERROR_LOG_CURRENT_EXPERIENCE}
error.log-self-employed=${ERROR_LOG_SELF_EMPLOYED}
error.log-company-owner=${ERROR_LOG_COMPANY_OWNER}
error.log-middle-manager=${ERROR_LOG_MIDDLE_MANAGER}
error.log-top-manager=${ERROR_LOG_TOP_MANAGER}
error.log-married=${ERROR_LOG_MARRIED}
error.log-divorced=${ERROR_LOG_DIVORCED}
error.log-female-discount=${ERROR_LOG_FEMALE_DISCOUNT}
error.log-male-discount=${ERROR_LOG_MALE_DISCOUNT}
error.log-non-binary-increase=${ERROR_LOG_NON_BINARY_INCREASE}