spring.application.name=calculator
server.port=${APP_PORT}

loan.base-interest=${LOAN_INTEREST}
loan.salary-decrease=${IF_SALARY_DECREASE}
loan.insurance-decrease=${IF_INSURANCE_DECREASE}

scoring.age.min=${CLIENT_MIN_AGE}
scoring.age.max=${CLIENT_MAX_AGE}

scoring.employment.self-employed-increase=${SELF_EMPLOYED_RATE_INCREASE}
scoring.employment.company-owner-increase=${COMPANY_OWNER_RATE_INCREASE}

scoring.position.middle-manager-decrease=${MIDDLE_MANAGER_RATE_DECREASE}
scoring.position.top-manager-decrease=${TOP_MANAGER_RATE_DECREASE}

scoring.marital.married-decrease=${MARRIED_RATE_DECREASE}
scoring.marital.divorced-increase=${DIVORCED_RATE_INCREASE}

scoring.salary.max-multiple=${MAX_MULTIPLE_OF_SALARY}

scoring.gender.female.age-min=${GENDER_FEMALE_AGE_MIN}
scoring.gender.female.age-max=${GENDER_FEMALE_AGE_MAX}
scoring.gender.male.age-min=${GENDER_MALE_AGE_MIN}
scoring.gender.male.age-max=${GENDER_MALE_AGE_MAX}

scoring.gender.female.decrease=${GENDER_FEMALE_RATE_DECREASE}
scoring.gender.male.decrease=${GENDER_MALE_RATE_DECREASE}
scoring.gender.non-binary.increase=${GENDER_NON_BINARY_RATE_INCREASE}

scoring.experience.total-min=${WORK_EXPERIENCE_TOTAL_MIN_MONTHS}
scoring.experience.current-min=${WORK_EXPERIENCE_CURRENT_MIN_MONTHS}