spring.application.name=calculator
server.port=${APP_PORT}

loan.base-interest=${BASE_INTEREST}
loan.salary-decrease=${IF_SALARY_DECREASE}
loan.insurance-decrease=${IF_INSURANCE_DECREASE}

scoring.min-age=${CLIENT_MIN_AGE}
scoring.max-age=${CLIENT_MAX_AGE}

scoring.self-employed-increase=${SELF_EMPLOYED_RATE_INCREASE}
scoring.company-owner-increase=${COMPANY_OWNER_RATE_INCREASE}

scoring.middle-manager-decrease=${MIDDLE_MANAGER_RATE_DECREASE}
scoring.top-manager-decrease=${TOP_MANAGER_RATE_DECREASE}

scoring.married-decrease=${MARRIED_RATE_DECREASE}
scoring.divorced-increase=${DIVORCED_RATE_INCREASE}

scoring.max-salary-multiple=${MAX_MULTIPLE_OF_SALARY}

scoring.female-age-min=${GENDER_FEMALE_AGE_MIN}
scoring.female-age-max=${GENDER_FEMALE_AGE_MAX}
scoring.male-age-min=${GENDER_MALE_AGE_MIN}
scoring.male-age-max=${GENDER_MALE_AGE_MAX}

scoring.female-decrease=${GENDER_FEMALE_RATE_DECREASE}
scoring.male-decrease=${GENDER_MALE_RATE_DECREASE}
scoring.non-binary-increase=${GENDER_NON_BINARY_RATE_INCREASE}

scoring.min-total-work-experience=${WORK_EXPERIENCE_TOTAL_MIN_MONTHS}
scoring.min-current-work-experience=${WORK_EXPERIENCE_CURRENT_MIN_MONTHS}

error.business-code=${ERROR_BUSINESS_CODE}
error.validation-code=${ERROR_VALIDATION_CODE}
error.server-code=${ERROR_SERVER_CODE}